const words = [

    // หน้า 1

    { chinese:"爱护", pinyin:"àihù", thai:"รักทะนุถนอม" },
    { chinese:"安检", pinyin:"ān jiǎn", thai:"การตรวจความปลอดภัย" },
    { chinese:"安静", pinyin:"ān jìng", thai:"เงียบสงบ" },
    { chinese:"安全带", pinyin:"ān quán dài", thai:"เข็มขัดนิรภัย" },
    { chinese:"按时", pinyin:"àn shí", thai:"ตรงเวลา" },
    { chinese:"暗示", pinyin:"ànshì", thai:"บอกเป็นนัย" },
    { chinese:"安慰", pinyin:"ānwèi", thai:"ปลอบโยน" },
    { chinese:"安装", pinyin:"ānzhuāng", thai:"ติดตั้ง" },
    { chinese:"奥秘", pinyin:"àomì", thai:"ความลึกลับ" },
    { chinese:"办法", pinyin:"bànfǎ", thai:"วิธีการ" },
    { chinese:"绑定", pinyin:"bǎngdìng", thai:"ผูกบัญชี" },
    { chinese:"帮忙", pinyin:"bāngmáng", thai:"ช่วยเหลือ" },
    { chinese:"班级", pinyin:"bānjí", thai:"ชั้นเรียน" },
    { chinese:"搬家", pinyin:"bānjiā", thai:"ย้ายบ้าน" },
    { chinese:"半径", pinyin:"bànjìng", thai:"รัศมี" },
    { chinese:"办理", pinyin:"bànlǐ", thai:"ดำเนินการ" },
    { chinese:"伴侣", pinyin:"bànlǚ", thai:"คู่ชีวิต" },
    { chinese:"版权", pinyin:"bǎnquán", thai:"ลิขสิทธิ์" },
    { chinese:"办事", pinyin:"bànshì", thai:"ทำธุระ" },
    { chinese:"保持", pinyin:"bǎochí", thai:"รักษาไว้" },

    // หน้า 2

    { chinese:"报道", pinyin:"bàodào", thai:"รายงานข่าว" },
    { chinese:"报复", pinyin:"bàofù", thai:"แก้แค้น" },
    { chinese:"保护", pinyin:"bǎohù", thai:"ปกป้อง" },
    { chinese:"报考", pinyin:"bàokǎo", thai:"สมัครสอบ" },
    { chinese:"保留", pinyin:"bǎoliú", thai:"เก็บไว้" },
    { chinese:"抱歉", pinyin:"bàoqiàn", thai:"ขอโทษ" },
    { chinese:"保守", pinyin:"bǎoshǒu", thai:"อนุรักษนิยม" },
    { chinese:"报销", pinyin:"bàoxiāo", thai:"เบิกค่าใช้จ่าย" },
    { chinese:"保养", pinyin:"bǎoyǎng", thai:"บำรุงรักษา" },
    { chinese:"报纸", pinyin:"bàozhǐ", thai:"หนังสือพิมพ์" },
    { chinese:"保质期", pinyin:"bǎozhìqī", thai:"ระยะเวลารับประกันคุณภาพ" },
    { chinese:"把握", pinyin:"bǎwò", thai:"ความมั่นใจ" },
    { chinese:"背包", pinyin:"bēibāo", thai:"กระเป๋าสะพาย" },
    { chinese:"北部", pinyin:"běibù", thai:"ภาคเหนือ" },
    { chinese:"被动", pinyin:"bèidòng", thai:"อยู่ในภาวะถูกกระทำ" },
    { chinese:"悲观", pinyin:"bēiguān", thai:"มองโลกในแง่ร้าย" },
    { chinese:"背景", pinyin:"bèijǐng", thai:"ภูมิหลัง" },
    { chinese:"背诵", pinyin:"bèisòng", thai:"ท่องจำ" },
    { chinese:"本科", pinyin:"běnkē", thai:"ปริญญาตรี" },
    { chinese:"本领", pinyin:"běnlǐng", thai:"ความสามารถ" },

    { chinese:"编号", pinyin:"biānhào", thai:"หมายเลขกำกับ" },
    { chinese:"编辑", pinyin:"biānjí", thai:"บรรณาธิการ" },
    { chinese:"便利店", pinyin:"biànlìdiàn", thai:"ร้านสะดวกซื้อ" },

    // ===== หน้า 5 =====

    { chinese:"测试", pinyin:"cèshì", thai:"ทดสอบ" },
    { chinese:"厕所", pinyin:"cèsuǒ", thai:"ห้องน้ำ" },
    { chinese:"差距", pinyin:"chājù", thai:"ความแตกต่าง" },
    { chinese:"查看", pinyin:"chákàn", thai:"ตรวจสอบ" },
    { chinese:"长度", pinyin:"chángdù", thai:"ความยาว" },
    { chinese:"尝试", pinyin:"chángshì", thai:"ทดลอง" },
    { chinese:"常识", pinyin:"chángshí", thai:"ความรู้ทั่วไป" },
    { chinese:"产生", pinyin:"chǎnshēng", thai:"ก่อให้เกิด" },
    { chinese:"产业", pinyin:"chǎnyè", thai:"อุตสาหกรรม" },
    { chinese:"超过", pinyin:"chāoguò", thai:"เกิน" },
    { chinese:"超越", pinyin:"chāoyuè", thai:"เหนือกว่า" },
    { chinese:"茶叶", pinyin:"cháyè", thai:"ใบชา" },
    { chinese:"查找", pinyin:"cházhǎo", thai:"ค้นหา" },
    { chinese:"彻底", pinyin:"chèdǐ", thai:"อย่างสิ้นเชิง" },
    { chinese:"乘", pinyin:"chéng", thai:"โดยสาร" },
    { chinese:"成本", pinyin:"chéngběn", thai:"ต้นทุน" },
    { chinese:"承担", pinyin:"chéngdān", thai:"รับผิดชอบ" },
    { chinese:"程度", pinyin:"chéngdù", thai:"ระดับ" },
    { chinese:"成分", pinyin:"chéngfèn", thai:"ส่วนประกอบ" },
    { chinese:"成功", pinyin:"chénggōng", thai:"ประสบความสำเร็จ" },
    { chinese:"成绩", pinyin:"chéngjì", thai:"คะแนน" },
    { chinese:"乘客", pinyin:"chéngkè", thai:"ผู้โดยสาร" },
    { chinese:"诚恳", pinyin:"chéngkěn", thai:"จริงใจ" },
        // ===== หน้า 6 =====

    { chinese:"成立", pinyin:"chénglì", thai:"ก่อตั้ง" },
    { chinese:"承认", pinyin:"chéngrèn", thai:"ยอมรับ" },
    { chinese:"诚实", pinyin:"chéngshí", thai:"ซื่อสัตย์" },
    { chinese:"成熟", pinyin:"chéngshú", thai:"เติบโตเต็มที่" },
    { chinese:"乘务员", pinyin:"chéngwùyuán", thai:"พนักงานต้อนรับบนยานพาหนะ" },
    { chinese:"程序", pinyin:"chéngxù", thai:"โปรแกรม" },
    { chinese:"成语", pinyin:"chéngyǔ", thai:"สำนวนจีน" },
    { chinese:"沉默", pinyin:"chénmò", thai:"เงียบงัน" },
    { chinese:"车速", pinyin:"chēsù", thai:"ความเร็วรถ" },
    { chinese:"吃惊", pinyin:"chījīng", thai:"ตกใจ" },
    { chinese:"吃亏", pinyin:"chīkuī", thai:"เสียเปรียบ" },
    { chinese:"持续", pinyin:"chíxù", thai:"ต่อเนื่อง" },
    { chinese:"迟早", pinyin:"chízǎo", thai:"ไม่ช้าก็เร็ว" },
    { chinese:"崇拜", pinyin:"chóngbài", thai:"เคารพบูชา" },
    { chinese:"充电", pinyin:"chōngdiàn", thai:"ชาร์จไฟ" },
    { chinese:"充分", pinyin:"chōngfèn", thai:"อย่างเพียงพอ" },
    { chinese:"重复", pinyin:"chóngfù", thai:"ทำซ้ำ" },
    { chinese:"充满", pinyin:"chōngmǎn", thai:"เต็มไปด้วย" },
    { chinese:"重新", pinyin:"chóngxīn", thai:"เริ่มใหม่อีกครั้ง" },
    { chinese:"抽象", pinyin:"chōuxiàng", thai:"นามธรรม" },
    { chinese:"传达", pinyin:"chuándá", thai:"แจ้ง" },
    { chinese:"窗户", pinyin:"chuānghu", thai:"หน้าต่าง" },

    // ===== หน้า 10 =====

    { chinese:"堵车", pinyin:"dǔchē", thai:"รถติด" },
    { chinese:"对待", pinyin:"duìdài", thai:"ปฏิบัติต่อ" },
    { chinese:"对方", pinyin:"duìfāng", thai:"ฝ่ายตรงข้าม" },
    { chinese:"兑换", pinyin:"duìhuàn", thai:"แลกเปลี่ยน" },
    { chinese:"队员", pinyin:"duìyuán", thai:"สมาชิกทีม" },
    { chinese:"度假", pinyin:"dùjià", thai:"ไปพักผ่อนวันหยุด" },
    { chinese:"独立", pinyin:"dúlì", thai:"เป็นอิสระ" },
    { chinese:"顿", pinyin:"dùn", thai:"มื้อ" },
    { chinese:"多数", pinyin:"duōshù", thai:"ส่วนใหญ่" },
    { chinese:"独特", pinyin:"dútè", thai:"มีเอกลักษณ์" },
    { chinese:"读者", pinyin:"dúzhě", thai:"ผู้อ่าน" },
    { chinese:"恩人", pinyin:"ēnrén", thai:"ผู้มีพระคุณ" },
    { chinese:"儿童", pinyin:"értóng", thai:"เด็ก" },
    { chinese:"二维码", pinyin:"èrwéimǎ", thai:"คิวอาร์โค้ด" },
    { chinese:"发达", pinyin:"fādá", thai:"พัฒนาเจริญ" },
    { chinese:"发挥", pinyin:"fāhuī", thai:"แสดงออก" },
    { chinese:"法律", pinyin:"fǎlǜ", thai:"กฎหมาย" },
    { chinese:"发明", pinyin:"fāmíng", thai:"ประดิษฐ์คิดค้น" },
    { chinese:"反复", pinyin:"fǎnfù", thai:"ซ้ำไปซ้ำมา" },
    { chinese:"房东", pinyin:"fángdōng", thai:"เจ้าของห้องเช่า" },
    { chinese:"放弃", pinyin:"fàngqì", thai:"ละทิ้ง" },
    { chinese:"方式", pinyin:"fāngshì", thai:"วิธีการ" },
    { chinese:"放松", pinyin:"fàngsōng", thai:"ผ่อนคลาย" },

    // ===== หน้า 12 =====

    { chinese:"符号", pinyin:"fú hào", thai:"สัญลักษณ์" },
    { chinese:"附件", pinyin:"fùjiàn", thai:"เอกสารแนบ" },
    { chinese:"付款", pinyin:"fùkuǎn", thai:"ชำระเงิน" },
    { chinese:"附属", pinyin:"fùshǔ", thai:"สังกัด" },
    { chinese:"服务", pinyin:"fú wù", thai:"บริการ" },
    { chinese:"复印", pinyin:"fù yìn", thai:"ถ่ายเอกสาร" },
    { chinese:"负责", pinyin:"fù zé", thai:"รับผิดชอบ" },
    { chinese:"负责人", pinyin:"fù zé rén", thai:"ผู้รับผิดชอบ" },
    { chinese:"改变", pinyin:"gǎi biàn", thai:"เปลี่ยนแปลง" },
    { chinese:"改革", pinyin:"gǎigé", thai:"ปฏิรูป" },
    { chinese:"概括", pinyin:"gàikuò", thai:"สรุปรวบยอด" },
    { chinese:"概念", pinyin:"gàiniàn", thai:"แนวคิด" },
    { chinese:"改善", pinyin:"gǎishàn", thai:"ปรับปรุงให้ดีขึ้น" },
    { chinese:"敢", pinyin:"gǎn", thai:"กล้า" },
    { chinese:"干脆", pinyin:"gāncuì", thai:"เด็ดขาด" },
    { chinese:"钢琴", pinyin:"gāng qín", thai:"เปียโน" },
    { chinese:"感激", pinyin:"gǎnjī", thai:"ซาบซึ้งขอบคุณ" },
    { chinese:"赶紧", pinyin:"gǎn jǐn", thai:"รีบ" },
    { chinese:"感受", pinyin:"gǎnshòu", thai:"ความรู้สึก" },
    { chinese:"感想", pinyin:"gǎnxiǎng", thai:"ความคิดเห็น" },
    { chinese:"高度", pinyin:"gāodù", thai:"ระดับความสูง" },
    { chinese:"高级", pinyin:"gāojí", thai:"ระดับสูง" },
];
